helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 900
  force: true

releases:
  - name: cassandra-db
    chart: bitnami/cassandra
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: database
      app: cassandra-db
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

  - name: cassandra-prometheus-sm
    chart: incubator/raw
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: workflow
      chart: cassandra-prometheus-sm
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
