helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true
  verify: false

releases:
  - name: cp-kafka
    chart: ../charts/cp-kafka
    installed: true
    namespace: default
    wait: true
    labels:
      component: data
      package-manager: helmfile
      chart: cp-kafka
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

  - name: kafka-create-topic
    chart: ../charts/raw
    wait: true
    installed: true
    namespace: default
    labels:
      component: workflow
      package-manager: helmfile
      chart: kafka-create-topic
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
