helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true

releases:
  - name: jaeger
    chart: incubator/jaeger
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: monitoring
      chart: jaeger
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
