helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true

releases:
  - name: local-path-storage
    chart: ../charts/raw
    installed: {{ eq .Environment.Name "default" }}
    namespace: default
    wait: true
    labels:
      component: monitoring
      package-manager: helmfile
      chart: local-path-storage
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.gotmpl

environments:
  default: {}
  gke: {}
