helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true

releases:
  - name: prometheus
    chart: ../charts/prometheus
    installed: true
    namespace: default
    wait: true
    labels:
      component: monitoring
      package-manager: helmfile
      chart: prometheus
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

  - name: grafana
    chart: ../charts/grafana
    installed: true
    namespace: default
    wait: true
    labels:
      component: monitoring
      package-manager: helmfile
      chart: grafana
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml
    set:
      - name: dashboards.default.cadence.json
        file: ../dashboards/cadence.json
      - name: dashboards.default.workflow.json
        file: ../dashboards/workflow.json

  - name: influxdb
    chart: ../charts/influxdb
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: monitoring
      chart: influxdb
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

  - name: jaeger
    chart: ../charts/jaeger
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: monitoring
      chart: jaeger
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
