helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true

releases:
  - name: prometheus-operator
    chart: stable/prometheus-operator
    installed: true
    namespace: default
    wait: true
    labels:
      component: monitoring
      package-manager: helmfile
      chart: prometheus-operator
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
