helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true

releases:
  - name: prometheus-pushgateway
    chart: stable/prometheus-pushgateway
    installed: {{ .Environment.Values | getOrNil "helmfile_install" | default false }}
    namespace: default
    wait: true
    labels:
      component: monitoring
      package-manager: helmfile
      chart: prometheus-pushgateway
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
