helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true

releases:
  - name: redis
    chart: stable/redis
    installed: true
    namespace: default
    wait: true
    labels:
      component: data
      package-manager: helmfile
      chart: mongodb
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
