helmDefaults:
  tillerNamespace: default
  tillerless: true
  timeout: 300
  force: true
  recreatePods: true

releases:
  - name: activities-wf-client
    chart: ../charts/cadence-sb-app
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: activities-wf-client
      chart: cadence-sb-app
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

  - name: sample-payment-wf-client
    chart: ../charts/cadence-sb-app
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: sample-payment-wf-client
      chart: cadence-sb-app
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

  - name: sample-payment-web
    chart: ../charts/cadence-sb-app
    wait: true
    installed: true
    namespace: default
    labels:
      package-manager: helmfile
      component: sample-payment-web
      chart: cadence-sb-app
    values:
      - ../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml

environments:
  default: {}
  gke: {}
