resources:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: cadence-create-keyspace
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
            - name: cadence-create-keyspace
              image: ubercadence/server:0.8.6
              env:
                - name: CASSANDRA_HOST
                  value: cassandra-db
                - name: CASSANDRA_USER
                  value: cassandra
                - name: CASSANDRA_PASSWORD
                  value: cassandra
              command:
                - bash
                - '-c'
                - |
                  set -x
                  echo "Started Running at $(date)"
                  # cassandra env
                  export KEYSPACE="${KEYSPACE:-cadence}"
                  export VISIBILITY_KEYSPACE="${VISIBILITY_KEYSPACE:-cadence_visibility}"
                  export CASSANDRA_PORT=9042
                  export CASSANDRA_USER=cassandra
                  export CASSANDRA_PASSWORD=cassandra
                  echo 'cassandra started'
                  cadence-cassandra-tool create -k $KEYSPACE --rf 3
                  cadence-cassandra-tool create -k $VISIBILITY_KEYSPACE --rf 1
                  echo 'cassandra schema for cadence ready'
          terminationGracePeriodSeconds: 30
          restartPolicy: OnFailure
