server:
  image:
    tag: 0.6.1
  logLevel: debug
  frontend:
    service:
      type: LoadBalancer
  matching:
    service:
      type: LoadBalancer
  history:
    numHistoryShards: 64
    service:
      type: LoadBalancer
  worker:
    service:
      type: LoadBalancer
web:
  image:
    tag: 3.3.2
cassandraVisibilityKeyspace: cadence_visibility
cassandra:
  image:
    tag: 3.11.4
  exporter:
    enabled: true
    image:
      repo: criteord/cassandra_exporter
      tag: 2.2.2
