resources:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: cadence-setup-job
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
            - env:
                - name: CADENCE_CLI_ADDRESS
                  value: cadence-frontend:7933
                - name: CADENCE_CLI_DOMAIN
                  value: megneto
              image: docker.io/ubercadence/cli:0.7.0
              name: cadence-setup-job
              command:
                - sh
                - '-c'
                - |
                  #!/bin/bash -ex
                  cadence --domain=magneto domain register --global_domain false
          terminationGracePeriodSeconds: 30
          restartPolicy: OnFailure
