resources:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        metrics-service: cassandra
      name: cassandra-metrics
    spec:
      ports:
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: cassandra
        release: cassandra-db
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      labels:
        app: cassandra
      name: cassandra
    spec:
      endpoints:
        - port: metrics
          scheme: http
          path: /
      jobLabel: cassandra
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          metrics-service: cassandra

