ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: gatling.gke
      paths:
        - /

gatling:
  repository: "gcr.io/frontal-23980c/gatling"
  tag: "3.2.1-0db44bc"