ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: gatling.gke
      paths:
        - path: /
          pathType: Prefix
tls: []

gatling:
  repository: "gcr.io/holograph-fda438/gatling"
  tag: "3.2.1-1"