resources:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        metrics-service: jaeger-collector
      name: jaeger-collector-metrics
    spec:
      ports:
        - name: metrics
          port: 14269
          protocol: TCP
          targetPort: 14269
      selector:
        app.kubernetes.io/component: collector
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/name: jaeger

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: jaeger-collector
    spec:
      endpoints:
        - port: metrics
          scheme: http
          path: /metrics
      jobLabel: jaeger-collector
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          metrics-service: jaeger-collector

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        metrics-service: jaeger-query
      name: jaeger-query-metrics
    spec:
      ports:
        - name: metrics
          port: 16687
          protocol: TCP
          targetPort: 16687
      selector:
        app.kubernetes.io/component: query
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/name: jaeger

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: jaeger-query
    spec:
      endpoints:
        - port: metrics
          scheme: http
          path: /metrics
      jobLabel: jaeger-query
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          metrics-service: jaeger-query
