resources:
  - apiVersion: jaegertracing.io/v1
    kind: Jaeger
    metadata:
      name: jaeger
    spec:
      strategy: allInOne
      ingress:
        enabled: false
      storage:
        type: memory
        options:
          memory:
            max-traces: 100000
      agent:
        strategy: DaemonSet

  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.class: traefik
      name: jaeger-query
    spec:
      rules:
      - host: jaeger-query.local
        http:
          paths:
          - backend:
              serviceName: jaeger-query
              servicePort: 16686
            path: /

  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.class: traefik
      name: jaeger-collector
    spec:
      rules:
        - host: jaeger-collector.local
          http:
            paths:
              - backend:
                  serviceName: jaeger-collector
                  servicePort: 14268
                path: /
