nameOverride: "prom"
fullnameOverride: "prom"
## Create default rules for monitoring the cluster
##
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    general: true
    k8s: true
    kubeApiserver: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubeScheduler: true
    kubernetesAbsent: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    node: true
    prometheusOperator: true
    prometheus: true
alertmanager:
  enabled: false
grafana:
  enabled: true
  adminPassword: admin
  ingress:
    enabled: true
    hosts:
    - grafana.gke
    annotations:
      kubernetes.io/ingress.class: traefik
    path: /
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      createPrometheusReplicasDatasources: false
      label: grafana_datasource
  additionalDataSources: []
  serviceMonitor:
    selfMonitor: true
  dashboards:
    default:
       cassandra:
         gnetId: 6258
         revision: 3
         datasource: Prometheus
       cadence:
         gnetId: 10373
         revision: 1
         datasource: Prometheus
       jvm-micrometer:
         gnetId: 4701
         revision: 8
         datasource: Prometheus

## Component scraping the kube api server
##
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false

prometheusOperator:
  cleanupCustomResourceBeforeInstall: true
  enabled: true
  logLevel: "all"
  tlsProxy:
    enabled: false
  serviceMonitor:
    interval: 15s

prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - prometheus.gke
    annotations:
      kubernetes.io/ingress.class: traefik
    path: /
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchNames:
        - default
    scrapeInterval: 15s
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.11.1
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 16Gi
