# Default values for temporal-sb-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: gcr.io/regolith-0a6bb2/temporal/sample-payment-activities-client
  tag: master-276720c

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: wf-activities.gke
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 3Gi

jvmOpts: "-Xms2g -Xmx2g"

configmap:
  gke: |-
    debug: false
    opentracing:
      jaeger:
        log-spans: false
        http-sender:
          url: http://jaeger-collector:14268/api/traces
        probabilistic-sampler:
          sampling-rate: 0.10
    spring:
      kafka:
        bootstrap-servers: cp-kafka:9092
      data:
        mongodb:
          uri: mongodb://temporal:temporal@mongodb:27017/temporal
      redis:
        password: redis
        host: redis-replicas
        port: 6379
    temporal:
      host: temporal-frontend
    server:
      port: 8080