resources:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: vegeta
        app.kubernetes.io/name: vegeta
      name: vegeta
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app.kubernetes.io/instance: vegeta
          app.kubernetes.io/name: vegeta
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: vegeta
            app.kubernetes.io/name: vegeta
        spec:
          containers:
            - name: vegeta
              image: gcr.io/monachism-83bea0/vegeta-nginx:0.0.2
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              ports:
                - containerPort: 80
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources: {}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app.kubernetes.io/instance: vegeta
        app.kubernetes.io/name: vegeta
      name: vegeta
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
      selector:
        app.kubernetes.io/instance: vegeta
        app.kubernetes.io/name: vegeta
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.class: traefik
      labels:
        app.kubernetes.io/instance: vegeta
        app.kubernetes.io/name: vegeta
      name: vegeta
    spec:
      rules:
        - host: vegeta.gke
          http:
            paths:
              - backend:
                  serviceName: vegeta
                  servicePort: http
                path: /
