{
 "title": "temporal frontend",
 "description": "An initial dashboard for prometheus metrics from https://github.com/temporalio/temporal",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "quantiles", "label": "Quantiles", "query": "0.5, 0.95, 0.99" }
  ]
 },
 "panels": [
  {
   "title": "Request Vs Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_errors[2m])",
     "legendFormat": "Errors - {{instance}}:{{operation}}:",
     "target": "fetch service:temporal-frontend deployment:$deployment name:{temporal_errors,temporal_requests} | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
    },
    {
     "expr": "rate(temporal_requests[2m])",
     "legendFormat": "Requests - {{instance}}:{{operation}}:{{domain}}"
    }
   ]
  },
  {
   "title": "Operation Latencies p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, sum(rate(persistence_latency_bucket[2m])) by (le, operation))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Error Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_errors_bad_request[2m])",
     "legendFormat": "bad_requests -   {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_bad_request | transformNull 0 | sum | scaleToSeconds 1 | alias BadRequest"
    },
    {
     "expr": "rate(temporal_errors_service_busy[2m])",
     "legendFormat": "service_busy -  {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_service_busy | transformNull 0 | sum | scaleToSeconds 1 | alias ServiceBusy"
    },
    {
     "expr": "rate(temporal_errors_entity_not_exists[2m])",
     "legendFormat": "entity_not_exists -   {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_entity_not_exists | transformNull 0 | sum | scaleToSeconds 1 | alias EntityNotExist"
    },
    {
     "expr": "rate(temporal_errors_execution_already_started[2m])",
     "legendFormat": "execution_already_started  -   {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_execution_already_started | transformNull 0 | sum | scaleToSeconds 1 | alias ExecutionAlreadyStarted"
    },
    {
     "expr": "rate(temporal_errors_domain_already_exists[2m])",
     "legendFormat": "domain_already_exists  -   {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_domain_already_exists | transformNull 0 | sum | scaleToSeconds 1 | alias DomainAlreadyExists"
    },
    {
     "expr": "rate(temporal_errors_cancellation_already_requested[2m])",
     "legendFormat": "cancellation_already_requested  -   {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_cancellation_already_requested | transformNull 0 | sum | scaleToSeconds 1 | alias CancellationAlreadyRequested"
    },
    {
     "expr": "rate(temporal_errors_context_timeout[2m])",
     "legendFormat": "errors_context_timeout  -   {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_context_timeout | transformNull 0 | sum | scaleToSeconds 1 | alias ContextTimeout"
    },
    {
     "expr": "rate(temporal_errors_limit_exceeded[2m])",
     "legendFormat": "limit_exceeded  -   {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_errors_limit_exceeded | transformNull 0 | sum | scaleToSeconds 1 | alias LimitExceeded"
    },
    {
     "expr": "rate(temporal_errors_query_failed[2m])",
     "legendFormat": "query_failed -   {{instance}}:{{operation}} : {{domain}}"
    },
    {
     "expr": "rate(temporal_errors_shard_ownership_lost[2m])",
     "legendFormat": "shard_ownership_lost -   {{instance}}:{{operation}} : {{domain}}"
    },
    {}
   ]
  },
  {
   "title": "Frontend API Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(temporal_latency_bucket[2m]))))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Frontend Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Frontend Client Request Vs Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_client_errors[2m])",
     "legendFormat": "errors -  {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:{temporal_client_errors,temporal_client_requests} | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
    },
    {
     "expr": "rate(temporal_client_requests[2m])",
     "legendFormat": "requests -   {{instance}}:{{operation}} : {{domain}}"
    }
   ]
  },
  {
   "title": "Frontend Client API Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(temporal_client_latency_bucket[2m]))))",
     "legendFormat": "{{operation}}",
     "target": "fetch service:temporal-frontend deployment:$deployment  name:temporal_client_latency timertype:$latency  | transformNull 0 | aliasByTags operation"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "StartWorfklowExecution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_requests{operation=\"StartWorkflowExecution\"}[2m])",
     "legendFormat": "requests -  {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:$service deployment:$deployment name:temporal_{errors_*,requests} operation:startworkflowexecution | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
    },
    {
     "expr": " rate(temporal_errors{ooperation=\"StartWorkflowExecution\"}[2m])",
     "legendFormat": "errors -  {{instance}}:{{operation}} : {{domain}}"
    }
   ]
  },
  {
   "title": "Operation Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, sum(rate(temporal_latency_bucket[2m])) by (le, operation))",
     "legendFormat": "{{operation}}",
     "target": "fetch service:$service deployment:$deployment timertype:{lower,median,p99,upper} operation:startworkflowexecution | transformNull 0 |  summarize 1min avg | avg timertype | aliasByTags timertype"
    }
   ]
  },
  {
   "title": "PollForActivityTask",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_requests{operation=\"PollForActivityTask\"}[2m])",
     "legendFormat": "requests -  {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:$service deployment:$deployment name:temporal_{errors_*,requests} operation:pollforactivitytask | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
    },
    {
     "expr": "rate(temporal_errors{operation=\"PollForActivityTask\"}[2m])",
     "legendFormat": "errors -  {{instance}}:{{operation}} : {{domain}}",
     "target": "fetch service:temporal-frontend deployment:$deployment name:temporal_requests operation:pollforactivitytask | sum | summarize 1m sum | diff (fetch service:temporal-frontend deployment:$deployment operation:pollforactivitytask name:temporal_errors | sum | summarize 1m sum) | asPercent (fetch service:temporal-frontend deployment:$deployment name:temporal_requests operation:pollforactivitytask | sum | summarize 1m sum) | transformNull 100 | alias availability"
    }
   ]
  },
  { "title": "Persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Requests Vs Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(persistence_errors[2m])",
     "legendFormat": "Errors - {{instance}}:{{operation}}:",
     "target": "fetch service:temporal-frontend deployment:$deployment name:persistence_{errors,requests}  | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
    },
    {
     "expr": "rate(persistence_requests[2m])",
     "legendFormat": "Requests - {{instance}}:{{operation}}:"
    }
   ]
  }
 ]
}