{
 "title": "Workflow Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Workflow Submit & Completed Statistics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workflow_request_submit_seconds_bucket[2m])) by (le))",
     "legendFormat": "Submit Latency"
    },
    {
     "expr": "sum(rate(workflow_request_submit_seconds_count{status=\"200\"}[2m]))",
     "legendFormat": "Submit Count"
    },
    {
     "expr": "sum(rate(workflow_request_seconds_count[2m]))",
     "legendFormat": "Completed Count"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(workflow_request_seconds_bucket[2m])) by (le))",
     "legendFormat": "E2E Latency"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Users",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "simulation" ], "type": "tag" }
     ],
     "measurement": "gatling.users",
     "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allUsers" }
     ]
    },
    {
     "alias": "Request: $tag_status",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "simulation" ], "type": "tag" },
      { "params": [ "request" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "pod cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[2m])*100)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Cadence DB Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(persistence_requests[5m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cadence DB Performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(persistence_latency_bucket[5m])) by (le, operation))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Loadtest Client Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_simulation ($col)",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "simulation" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "percentile 99" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "app cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (application) (process_cpu_usage)",
     "legendFormat": "Process {{ application }}"
    }
   ]
  },
  {
   "title": "Cadence Operation Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_latency_sum[3m])) by (type, operation)",
     "legendFormat": "Latency: {{type}}-{{operation}}"
    },
    {
     "expr": "sum(rate(cadence_latency_count[3m])) by (type, operation)",
     "legendFormat": "Count: {{type}}-{{operation}}"
    }
   ]
  },
  {
   "title": "PollForActivityTask",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_PollForActivityTask_cadence_latency_seconds_sum[3m])) ",
     "legendFormat": "Client Latency"
    },
    {
     "expr": "sum(rate(cadence_latency_sum{operation=\"PollForActivityTask\"}[3m])) by (type, operation)",
     "legendFormat": "Cadence Latency: {{type}}-{{operation}}"
    },
    {
     "expr": "sum(rate(cadence_PollForActivityTask_cadence_latency_seconds_count[3m])) ",
     "legendFormat": "Client Count: "
    },
    {
     "expr": "sum(rate(cadence_latency_count{operation=\"PollForActivityTask\"}[3m])) by (type, operation)",
     "legendFormat": "Cadence Count: {{type}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Request Vs Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(cadence_errors[2m])) by(operation)",
     "legendFormat": "Errors - {{operation}}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:{cadence_errors,cadence_requests} | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
    },
    {
     "expr": "sum(rate(cadence_requests[2m])) by(operation)",
     "legendFormat": "Requests - {{operation}}:{{domain}}"
    }
   ]
  }
 ]
}