{
 "title": "Workflow",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Workflow Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_workflow_endtoend_latency_seconds_count[1m]))",
     "legendFormat": "Workflow Count"
    },
    {
     "expr": "sum(rate(cadence_activity_endtoend_latency_seconds_count[1m]))",
     "legendFormat": "Activity Count"
    },
    {
     "expr": "sum(rate(cadence_workflow_endtoend_latency_seconds_sum[1m]))/sum(rate(cadence_workflow_endtoend_latency_seconds_count[1m]))",
     "legendFormat": "Workflow Latency"
    },
    {
     "expr": "sum(rate(cadence_activity_endtoend_latency_seconds_sum[1m]))/sum(rate(cadence_activity_endtoend_latency_seconds_count[1m]))",
     "legendFormat": "Activity Latency"
    }
   ]
  },
  {
   "title": "app cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (process_cpu_usage)*100 ",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "pod cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m])*100)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}