debug: false
spring:
  application:
    name: processfile-wf

opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: http://jaeger-collector.local/api/traces
    enable-b3-propagation: true
    tags:
      wf: processfile
  spring:
    web:
      enabled: false
    cloud:
      async:
        enabled: false
management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: pushgateway.local
          push-rate: 15s
          grouping-key:
            wf: demo
cadence:
  host: cadence
  port: 7933
  emit-metric: true
  retention-period: 10d
logging:
  level:
    com.anz: debug
    io.jaegertracing.internal.reporters.LoggingReporter: warn
