{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "cassandra.fullname" . }}
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ template "cassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "cassandra.name" . }}
      release: {{ .Release.Name }}
  ingress:
    # Allow inbound connections
    # CQL and Thrift ports
    - ports:
      - port: {{ .Values.service.port }}
      - port: {{ .Values.service.thriftPort }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "cassandra.fullname" . }}-client: "true"
      {{- end }}
        - podSelector:
            matchLabels:
              app: {{ template "cassandra.name" . }}
              release: {{ .Release.Name }}
    # Internal ports
    - ports:
      - port: intra
      - port: tls
      - port: jmx
      from:
        - podSelector:
            matchLabels:
              app: {{ template "cassandra.name" . }}
              release: {{ .Release.Name }}
    {{- if .Values.metrics.enabled }}
    # Allow prometheus scrapes for metrics
    - ports:
      - port: 8080
    {{- end }}
{{- end }}
