apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatling.fullname" . }}
  labels:
{{ include "gatling.labels" . | indent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gatling.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gatling.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        {{- if .Values.gatling.conf }}
        checksum/gatling-conf: {{ include (print $.Template.BasePath "/gatling-conf-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.gatling.resources }}
        checksum/gatling-resources: {{ include (print $.Template.BasePath "/gatling-resources-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.gatling.simulations }}
        checksum/gatling-simulations: {{ include (print $.Template.BasePath "/gatling-simulations-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: gatling
          image: "{{ .Values.gatling.repository }}:{{ .Values.gatling.tag }}"
          imagePullPolicy: {{ .Values.gatling.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /opt/gatling/results

            {{- if .Values.gatling.conf }}
            {{- range $filename, $content := .Values.gatling.conf }}
            - name: gatling-conf
              mountPath: /opt/gatling/conf/{{ $filename }}
              subPath: {{ $filename }}
            {{- end }}
            {{- end }}

            {{- if .Values.gatling.resources }}
            {{- range $filename, $content := .Values.gatling.resources }}
            - name: gatling-resources
              mountPath: /opt/gatling/user-files/resources/{{ $filename }}
              subPath: {{ $filename }}
            {{- end }}
            {{- end }}

            {{- if .Values.gatling.simulations }}
            {{- range $filename, $content := .Values.gatling.simulations }}
            - name: gatling-simulations
              mountPath: /opt/gatling/user-files/simulations/{{ $filename }}
              subPath: {{ $filename }}
            {{- end }}
            {{- end }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 4
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 8
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: data
              mountPath: /usr/share/nginx/html
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "gatling.fullname" . }}
        - name: nginx-config
          configMap:
            name: {{ include "gatling.fullname" $ }}-nginx
        {{- if .Values.gatling.conf }}
        - name: gatling-conf
          configMap:
            name: {{ include "gatling.fullname" $ }}-conf
        {{- end }}
        {{- if .Values.gatling.resources }}
        - name: gatling-resources
          configMap:
            name: {{ include "gatling.fullname" $ }}-resources
        {{- end }}
        {{- if .Values.gatling.simulations }}
        - name: gatling-simulations
          configMap:
            name: {{ include "gatling.fullname" $ }}-simulations
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
