apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "gatling.fullname" . }}-nginx"
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gatling.labels" . | indent 4 }}
data:
{{- if .Values.nginx.conf }}
  default.conf: |
{{ .Values.nginx.conf | indent 4 }}
{{- end }}
