{{- if .Values.server.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.fullname" . }}-frontend
  labels:
    cadence-service: frontend
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    helm.sh/chart: {{ include "cadence.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.server.frontend.service.type }}
  ports:
    - port: {{ .Values.server.frontend.service.port }}
      targetPort: {{ .Values.server.frontend.service.port }}
      protocol: TCP
      name: frontend
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: frontend-metrics
  selector:
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---

{{- if .Values.server.matching.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.fullname" . }}-matching
  labels:
    cadence-service: matching
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    helm.sh/chart: {{ include "cadence.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.server.matching.service.type }}
  ports:
    - port: {{ .Values.server.matching.service.port }}
      targetPort: {{ .Values.server.matching.service.port }}
      protocol: TCP
      name: matching
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: matching-metrics
  selector:
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---

{{- if .Values.server.history.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.fullname" . }}-history
  labels:
    cadence-service: history
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    helm.sh/chart: {{ include "cadence.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8002"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.server.history.service.type }}
  ports:
    - port: {{ .Values.server.history.service.port }}
      targetPort: {{ .Values.server.history.service.port }}
      protocol: TCP
      name: history
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: history-metrics
  selector:
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---

{{- if .Values.server.worker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.fullname" . }}-worker
  labels:
    cadence-service: worker
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    helm.sh/chart: {{ include "cadence.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8003"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.server.worker.service.type }}
  ports:
    - port: {{ .Values.server.worker.service.port }}
      targetPort: {{ .Values.server.worker.service.port }}
      protocol: TCP
      name: worker
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: worker-metrics
  selector:
    app.kubernetes.io/name: {{ include "cadence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

