{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "cadence.name" . }}-web
    helm.sh/chart: {{ include "cadence.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.web.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .Values.web.service.loadBalancerIP }}
  loadBalancerIP: {{.}}
{{- end }}
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cadence.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}