apiVersion: v1
appVersion: 3.11.4
description: Apache Cassandra is a free and open-source distributed database management
  system designed to handle large amounts of data across many commodity servers, providing
  high availability with no single point of failure. Cassandra offers robust support
  for clusters spanning multiple datacenters, with asynchronous masterless replication
  allowing low latency operations for all clients.
engine: gotpl
home: http://cassandra.apache.org
icon: https://bitnami.com/assets/stacks/cassandra/img/cassandra-stack-220x234.png
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: cassandra
sources:
- https://github.com/bitnami/bitnami-docker-cassandra
version: 3.4.0
