helmDefaults:
  timeout: 1200
  wait: true

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com

helmfiles:
  - releases/local-path-storage.yaml
  - releases/traefik.yaml
#  - releases/cadence.yaml
#  - releases/jaeger.yaml
#  - releases/prometheus-operator.yaml
#  - releases/prometheus-service-monitor.yaml
#  - releases/prometheus-pushgateway.yaml

environments:
  defaults: {}
  gke: {}
