helmDefaults:
  timeout: 1800
  wait: true

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmfiles:
  - releases/local-path-storage.yaml
  - releases/traefik.yaml
  - releases/cassandra-db.yaml
  - releases/cp-kafka.yaml
  - releases/mongodb.yaml
  - releases/redis.yaml
  - releases/jaeger.yaml
  - releases/prometheus.yaml
  - releases/cadence.yaml
  - releases/magneto.yaml

environments:
  defaults: {}
  gke: {}
