apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "magneto-sb-app.fullname" . }}
  labels:
{{ include "magneto-sb-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "magneto-sb-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "magneto-sb-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "OPENTRACING_JAEGER_HTTPSENDER_URL"
              value: "http://{{ .Values.jaeger.collectorHost }}/api/traces"
            - name: "CADENCE_HOST"
              value: {{ .Values.cadence.host | quote }}
            - name: "CADENCE_PORT"
              value: {{ .Values.cadence.port | default "7933" | quote }}
            - name: "JAVA_TOOL_OPTIONS"
              value: {{ .Values.jvmOpts | default "" | quote }}
            - name: "SERVER_SERVLET_CONTEXT_PATH"
              value: {{ .Values.contextPath | default "/" | quote }}
            - name: "SPRING_PROFILES_ACTIVE"
              value: {{ .Values.spring.profiles.active | default "gke" | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
