log:
  stdout: true
  level: {{ default .Env.LOG_LEVEL "info" }}

persistence:
  numHistoryShards: {{ default .Env.NUM_HISTORY_SHARDS "4" }}
  defaultStore: default
  visibilityStore: visibility
  datastores:
    {{- $db := default .Env.DB "cassandra" | lower -}}
      {{- if eq $db "cassandra" }}
      default:
        cassandra:
          hosts: {{ default .Env.CASSANDRA_SEEDS "" }}
          keyspace: {{ default .Env.KEYSPACE "cadence" }}
          consistency: {{ default .Env.CASSANDRA_CONSISTENCY "One" }}
          user: cassandra
          password: cassandra
      visibility:
        cassandra:
          hosts: {{ default .Env.CASSANDRA_SEEDS "" }}
          keyspace: {{ default .Env.VISIBILITY_KEYSPACE "cadence" }}
          consistency: {{ default .Env.CASSANDRA_CONSISTENCY "One" }}
          user: cassandra
          password: cassandra
      {{- else if eq $db "mysql" }}
      default:
        sql:
          driverName: "mysql"
          databaseName: {{ default .Env.DBNAME "cadence" }}
          connectAddr: "{{ default .Env.MYSQL_SEEDS "" }}:{{ default .Env.DB_PORT "3306" }}"
          connectProtocol: "tcp"
          user: {{ default .Env.MYSQL_USER "" }}
          password: {{ default .Env.MYSQL_PWD "" }}
      visibility:
        sql:
          driverName: "mysql"
          databaseName: {{ default .Env.VISIBILITY_DBNAME "cadence_visibility" }}
          connectAddr: "{{ default .Env.MYSQL_SEEDS "" }}:{{ default .Env.DB_PORT "3306" }}"
          connectProtocol: "tcp"
          user: {{ default .Env.MYSQL_USER "" }}
          password: {{ default .Env.MYSQL_PWD "" }}
      {{- end }}

ringpop:
  name: cadence
  bootstrapMode: hosts
  {{- if .Env.RINGPOP_SEEDS }}
  bootstrapHosts:
  {{- range $seed := (split .Env.RINGPOP_SEEDS ",") }}
    - {{ . }}
  {{- end }}
  {{- else }}
  bootstrapHosts:
    - {{ default .Env.BIND_ON_IP "127.0.0.1" }}:7933
    - {{ default .Env.BIND_ON_IP "127.0.0.1" }}:7934
    - {{ default .Env.BIND_ON_IP "127.0.0.1" }}:7935
    - {{ default .Env.BIND_ON_IP "127.0.0.1" }}:7939
  {{- end }}
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 7933
      bindOnIP: {{ default .Env.BIND_ON_IP "0.0.0.0" }}
    metrics:
      tags:
        cadence-service: frontend
      prometheus:
        timerType: "histogram"
        listenAddress: {{ default .Env.BIND_ON_IP "0.0.0.0" }}:8000

  matching:
    rpc:
      port: 7935
      bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
    metrics:
      tags:
        cadence-service: matching
      prometheus:
        timerType: "histogram"
        listenAddress: {{ default .Env.BIND_ON_IP "0.0.0.0" }}:8001

  history:
    rpc:
      port: 7934
      bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
    metrics:
      tags:
        cadence-service: history
      prometheus:
        timerType: "histogram"
        listenAddress: {{ default .Env.BIND_ON_IP "0.0.0.0" }}:8002

  worker:
    rpc:
      port: 7939
      bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
    metrics:
      tags:
        cadence-service: worker
      prometheus:
        timerType: "histogram"
        listenAddress: {{ default .Env.BIND_ON_IP "0.0.0.0" }}:8003

clusterMetadata:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: "127.0.0.1:7933"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  status: "disabled"
  enableReadFromArchival: false
  defaultBucket: "cadence-development"
  filestore:
    storeDirectory: "/tmp/development/blobstore/"
    defaultBucket: "cadence-development"
    customBuckets:
      - "custom-bucket-1"
      - "custom-bucket-2"

kafka:
  tls:
    enabled: false
  clusters:
    test:
      brokers:
        - {{ default .Env.KAFKA_SEEDS "" }}:9092
  topics:
    cadence-visibility-dev:
      cluster: test
    cadence-visibility-dev-dlq:
      cluster: test
  applications:
    visibility:
      topic: cadence-visibility-dev
      dlq-topic: cadence-visibility-dev-dlq

elasticsearch:
  enable: false
  url:
    scheme: "http"
    host: "{{ default .Env.ES_SEEDS "" }}:9200"
  indices:
    visibility: cadence-visibility-dev

publicClient:
  hostPort: {{ default .Env.BIND_ON_IP "127.0.0.1" }}:7933

dynamicConfigClient:
  filepath: {{ default .Env.DYNAMIC_CONFIG_FILE_PATH "/etc/cadence/config/dynamicconfig" }}
  pollInterval: "60s"
