debug: true

spring:
  application:
    name: ${projectName}
  jackson:
    default-property-inclusion: non_empty
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    mongodb:
      #uri: mongodb://magneto:magneto@localhost:27017/magneto
  redis:
    #password: redis
    host: localhost
    port: 6379
  kafka:
    producer:
      key-serializer:
opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: http://localhost:14268/api/traces
    enable-b3-propagation: true
    tags:
      component: ${projectName}
    service-name: magneto
  spring:
    cloud:
      async:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

cadence:
  host: localhost
  port: 7933
  emit-metric: true
  retention-period: 1d

logging:
  level:
    com.anz: debug
    io.jaegertracing.internal.reporters.LoggingReporter: warn
