debug: true
spring:
  application:
    name: ${projectName}

opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: http://jaeger-collector.local/api/traces
    enable-b3-propagation: true
    tags:
      component: ${projectName}
    service-name: magneto
  spring:
    cloud:
      async:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
cadence:
  host: cadence
  port: 7933
  emit-metric: true
  retention-period: 1d
logging:
  level:
    com.anz: debug
    io.jaegertracing.internal.reporters.LoggingReporter: warn
