debug: false
opentracing:
  jaeger:
    log-spans: false
    http-sender:
      url: http://jaeger-collector:14268/api/traces
    probabilistic-sampler:
      sampling-rate: 0.10
spring:
  kafka:
    bootstrap-servers: cp-kafka-headless:9092
  data:
    mongodb:
      uri: mongodb://temporal:temporal@mongodb-headless:27017/temporal
  redis:
    password: redis
    host: redis-headless
    port: 6379
temporal:
  host: temporal-frontend-headless
server:
  port: 8080
