//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 04:40:22 PM AEST
//


package com.anz.magneto.model.wrapper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.anz.PSPHeader_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="com.anz.PSPHeader_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ComponentName" type="{http://schema.cmo.anz/PSPWrapperObject}string35"/>
 *         &lt;element name="ReplyToQueue" type="{http://schema.cmo.anz/PSPWrapperObject}string80"/>
 *         &lt;element name="ServiceAction" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.Service_Action"/>
 *         &lt;element name="ReqMap" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.Misc_Map"/>		   
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.anz.PSPHeader_Type", namespace = "http://schema.cmo.anz/PSPWrapperObject", propOrder = {
        "UUID",
        "workFlow",
        "componentName",
        "replyToQueue",
        "serviceAction",
        "reqMap"
})
public class ComAnzPSPHeaderType {

    @XmlElement(name = "UUID", required = true)
    protected String UUID;
    @XmlElement(name = "WorkFlow", required = true)
    protected String workFlow;
    @XmlElement(name = "ComponentName", required = true)
    protected String componentName;
    @XmlElement(name = "ReplyToQueue", required = true)
    protected String replyToQueue;
    @XmlElement(name = "ServiceAction", required = true)
    protected ComAnzServiceAction serviceAction;
    @XmlElement(name = "ReqMap", required = true)
    protected ComAnzMiscMap reqMap;
	

    /**
     * Gets the value of the componentName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * Sets the value of the componentName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setComponentName(String value) {
        this.componentName = value;
    }

    /**
     * Gets the value of the replyToQueue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReplyToQueue() {
        return replyToQueue;
    }

    /**
     * Sets the value of the replyToQueue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReplyToQueue(String value) {
        this.replyToQueue = value;
    }

    /**
     * Gets the value of the serviceAction property.
     *
     * @return
     *     possible object is
     *     {@link ComAnzServiceAction }
     *
     */
    public ComAnzServiceAction getServiceAction() {
        return serviceAction;
    }

    /**
     * Sets the value of the serviceAction property.
     *
     * @param value
     *     allowed object is
     *     {@link ComAnzServiceAction }
     *
     */
    public void setServiceAction(ComAnzServiceAction value) {
        this.serviceAction = value;
    }

    /**
     * Gets the value of the reqMap property.
     *
     * @return
     *     possible object is
     *     {@link ComAnzMiscMap }
     *
     */
    public ComAnzMiscMap getReqMap() {
        return reqMap;
    }

    /**
     * Sets the value of the reqMap property.
     *
     * @param value
     *     allowed object is
     *     {@link ComAnzMiscMap }
     *
     */
    public void setReqMap(ComAnzMiscMap value) {
        this.reqMap = value;
    }

    /**
     * Gets the value of the uuid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUUID() {
        return UUID;
    }

    /**
     * Sets the value of the uuid property.
     *
     * @param UUID
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUUID(String UUID) {
        this.UUID = UUID;
    }

    /**
     * Gets the value of the work flow property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWorkFlow() {
        return workFlow;
    }

    /**
     * Sets the value of the work flow property.
     *
     * @param workFlow
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWorkFlow(String workFlow) {
        this.workFlow = workFlow;
    }	
	
}
