//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.04 at 04:40:22 PM AEST
//


package com.anz.magneto.model.wrapper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.anz.PSPTrailer_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="com.anz.PSPTrailer_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceStatus" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.Service_Status"/>
 *         &lt;element name="ResMap" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.Misc_Map"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.anz.PSPTrailer_Type", namespace = "http://schema.cmo.anz/PSPWrapperObject", propOrder = {
        "serviceStatus",
        "resMap"
})
public class ComAnzPSPTrailerType {

    @XmlElement(name = "ServiceStatus", required = true)
    protected ComAnzServiceStatus serviceStatus;
    @XmlElement(name = "ResMap", required = true)
    protected ComAnzMiscMap resMap;

    /**
     * Gets the value of the serviceStatus property.
     *
     * @return
     *     possible object is
     *     {@link ComAnzServiceStatus }
     *
     */
    public ComAnzServiceStatus getServiceStatus() {
        return serviceStatus;
    }

    /**
     * Sets the value of the serviceStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link ComAnzServiceStatus }
     *
     */
    public void setServiceStatus(ComAnzServiceStatus value) {
        this.serviceStatus = value;
    }

    /**
     * Gets the value of the resMap property.
     *
     * @return
     *     possible object is
     *     {@link ComAnzMiscMap }
     *
     */
    public ComAnzMiscMap getResMap() {
        return resMap;
    }

    /**
     * Sets the value of the resMap property.
     *
     * @param value
     *     allowed object is
     *     {@link ComAnzMiscMap }
     *
     */
    public void setResMap(ComAnzMiscMap value) {
        this.resMap = value;
    }

}
