//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.14 at 03:36:19 PM AEDT 
//


package com.anz.magneto.model.wrapper;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.anz.Accounting_Entry_Map complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.anz.Accounting_Entry_Map">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountingEntry" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.Accounting_Entry_Map_Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.anz.Accounting_Entry_Map", namespace = "http://schema.cmo.anz/PSPWrapperObject", propOrder = {
    "accountingEntry"
})
public class ComAnzAccountingEntryMap {

    @XmlElement(name = "AccountingEntry")
    protected List<ComAnzAccountingEntryMapType> accountingEntry;

    /**
     * Gets the value of the accountingEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountingEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountingEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComAnzAccountingEntryMapType }
     * 
     * 
     */
    public List<ComAnzAccountingEntryMapType> getAccountingEntry() {
        if (accountingEntry == null) {
            accountingEntry = new ArrayList<ComAnzAccountingEntryMapType>();
        }
        return this.accountingEntry;
    }

}
