//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.08.04 at 02:21:35 PM AEST
//


package com.anz.magneto.model.wrapper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.anz.Misc_Map_Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="com.anz.Misc_Map_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MapKey" type="{http://schema.cmo.anz/PSPWrapperObject}string10" minOccurs="0"/>
 *         &lt;element name="MapValue" type="{http://schema.cmo.anz/PSPWrapperObject}string255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.anz.Misc_Map_Type", namespace = "http://schema.cmo.anz/PSPWrapperObject", propOrder = {
        "mapKey",
        "mapValue"
})
public class ComAnzMiscMapType {

    @XmlElement(name = "MapKey")
    protected String mapKey;
    @XmlElement(name = "MapValue")
    protected String mapValue;

    /**
     * Gets the value of the mapKey property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMapKey() {
        return mapKey;
    }

    /**
     * Sets the value of the mapKey property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMapKey(String value) {
        this.mapKey = value;
    }

    /**
     * Gets the value of the mapValue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMapValue() {
        return mapValue;
    }

    /**
     * Sets the value of the mapValue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMapValue(String value) {
        this.mapValue = value;
    }

}
