//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 01:06:56 PM AEST
//


package com.anz.magneto.model.wrapper;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.anz.psp.commons.model.wrapper package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PmtAddRq_QNAME = new QName("http://schema.cmo.anz/PmtAdd", "PmtAddRq");
    private final static QName _PmtAddRs_QNAME = new QName("http://schema.cmo.anz/PmtAdd", "PmtAddRs");
    private final static QName _PmtRsAck_QNAME = new QName("http://schema.cmo.anz/PmtAdd", "PmtRsAck");
    private final static QName _PmtEnqRq_QNAME = new QName("http://schema.cmo.anz/PmtAdd", "PmtEnqRq");
    private static final String SCHEMA_PMT_ADD = "http://schema.cmo.anz/PmtAdd";
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anz.psp.commons.model.wrapper
     *
     */
    public ObjectFactory() {
    	// Default Constructor
    }

    /**
     * Create an instance of {@link PSPWrapperObject }
     *
     */
    public PSPWrapperObject createPSPWrapperObject() {
        return new PSPWrapperObject();
    }

    /**
     * Create an instance of {@link ComAnzPSPBodyType }
     *
     */
    public ComAnzPSPBodyType createComAnzPSPBodyType() {
        return new ComAnzPSPBodyType();
    }

    /**
     * Create an instance of {@link ComAnzPSPHeaderType }
     *
     */
    public ComAnzPSPHeaderType createComAnzPSPHeaderType() {
        return new ComAnzPSPHeaderType();
    }

    /**
     * Create an instance of {@link ComAnzMiscMapType }
     *
     */
    public ComAnzMiscMapType createComAnzMiscMapType() {
        return new ComAnzMiscMapType();
    }

    /**
     * Create an instance of {@link ComAnzServiceAction }
     *
     */
    public ComAnzServiceAction createComAnzServiceAction() {
        return new ComAnzServiceAction();
    }

    /**
     * Create an instance of {@link ComAnzPSPTrailerType }
     *
     */
    public ComAnzPSPTrailerType createComAnzPSPTrailerType() {
        return new ComAnzPSPTrailerType();
    }

    /**
     * Create an instance of {@link ComAnzMiscMap }
     *
     */
    public ComAnzMiscMap createComAnzMiscMap() {
        return new ComAnzMiscMap();
    }

    /**
     * Create an instance of {@link ComAnzServiceStatus }
     *
     */
    public ComAnzServiceStatus createComAnzServiceStatus() {
        return new ComAnzServiceStatus();
    }

	/**
     * Create an instance of {@link ComAnzAccountingEntryMapType }
     * 
     */
    public ComAnzAccountingEntryMapType createComAnzAccountingEntryMapType() {
        return new ComAnzAccountingEntryMapType();
    }
	
	/**
     * Create an instance of {@link ComAnzAccountingEntryMap }
     * 
     */
    public ComAnzAccountingEntryMap createComAnzAccountingEntryMap() {
        return new ComAnzAccountingEntryMap();
    }
    
    /**
     * Create an instance of {@link PSPAcctWrapperObject }
     * 
     */
    public PSPAcctWrapperObject createPSPAcctWrapperObject() {
        return new PSPAcctWrapperObject();
    }
}
