//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.08.04 at 04:24:16 PM AEST
//


package com.anz.magneto.model.wrapper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PSPWrapperObject complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PSPWrapperObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.PSPHeader_Type"/>
 *         &lt;element name="Body" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.PSPBody_Type"/>
 *         &lt;element name="Trailer" type="{http://schema.cmo.anz/PSPWrapperObject}com.anz.PSPTrailer_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PSPWrapperObject", namespace = "http://schema.cmo.anz/PSPWrapperObject", propOrder = {
		"header",
		"body",
		"trailer"
})
@XmlSeeAlso({
    PSPAcctWrapperObject.class
})
public class PSPWrapperObject {

	@XmlElement(name = "Header", required = true)
	protected ComAnzPSPHeaderType header;
	@XmlElement(name = "Body", required = true)
	protected ComAnzPSPBodyType body;
	@XmlElement(name = "Trailer", required = true)
	protected ComAnzPSPTrailerType trailer;

	/**
	 * Gets the value of the header property.
	 *
	 * @return
	 *     possible object is
	 *     {@link ComAnzPSPHeaderType }
	 *
	 */
	public ComAnzPSPHeaderType getHeader() {
		return header;
	}

	/**
	 * Sets the value of the header property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link ComAnzPSPHeaderType }
	 *
	 */
	public void setHeader(ComAnzPSPHeaderType value) {
		this.header = value;
	}

	/**
	 * Gets the value of the body property.
	 *
	 * @return
	 *     possible object is
	 *     {@link ComAnzPSPBodyType }
	 *
	 */
	public ComAnzPSPBodyType getBody() {
		return body;
	}

	/**
	 * Sets the value of the body property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link ComAnzPSPBodyType }
	 *
	 */
	public void setBody(ComAnzPSPBodyType value) {
		this.body = value;
	}

	/**
	 * Gets the value of the trailer property.
	 *
	 * @return
	 *     possible object is
	 *     {@link ComAnzPSPTrailerType }
	 *
	 */
	public ComAnzPSPTrailerType getTrailer() {
		return trailer;
	}

	/**
	 * Sets the value of the trailer property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link ComAnzPSPTrailerType }
	 *
	 */
	public void setTrailer(ComAnzPSPTrailerType value) {
		this.trailer = value;
	}

}
